### ISSUE TITLE
Changing the time of one existing alarm to another existing alarm crashes the app

### ISSUE THREAD

**Issue by NekoSoftVinhTQ** [WrichikBasu/ShakeAlarmClock#66]
i have 2 alarms with different time. When I edit one alarm to match the other alarm's time, I get the following error. please help me fix it.
![image](https://github.com/WrichikBasu/ShakeAlarmClock/assets/139045494/1e1adbc7-d0cb-45d0-a1cc-cfb5e4d8e4ba)

**Comment by lehuy2k1** [comment]
I also got the same error

**Comment by WrichikBasu** [comment]
Sorry for the very late reply, got really involved in some personal work. I will test and review this. Thanks for reporting.

**Comment by WrichikBasu** [comment]
This is going to be one of those difficult bugs. Having a hard time finding the root cause.
