### ISSUE TITLE
Material Icon

### ISSUE THREAD

**Issue by ghost** [WrichikBasu/ShakeAlarmClock#78]
Hey,

all of my Apps are in the same theme from Material Icon but only Shake Alarm Clock is not matching. Could you add Material Icon that it can match with my other Apps too? Because it bothers me a bit, that it stands out as only.

**Comment by WrichikBasu** [comment]
Sorry, but I am not going to change the icon.

Btw most of your issues are basically feature requests, except one that reports an issue. From next time onwards, please open a discussion for feature requests.

**Comment by ghost** [comment]
> Sorry, but I am not going to change the icon.

But that does not change the Icon. It just gives the one who use material icon theme, the ability to have it all the same. Your App Icon stays the same. I really don't understand why not?

> Btw most of your issues are basically feature requests, except one that reports an issue. From next time onwards, please open a discussion for feature requests.

Oh, I'm so sorry about that! Your totally right. I did not know to handle it like that, because I haven't used Github much. I saw from others that they did the same and I guessed, that it is normal. And because some Github Pages from Apps does not have Discussion Area, that let me used to this. Sorry for the inconvenience!
