### ISSUE TITLE
Target SDK

### ISSUE THREAD

**Issue by ghost** [WrichikBasu/ShakeAlarmClock#79]
Hey,

since Android 15 is launched, could you make the Target SDK to 35 that it gets well supported for the App?

**Comment by WrichikBasu** [comment]
Yeah, I will have to do it. As far as I saw, there are no behaviour changes that will affect this app, so the upgrade should be straightforward. Have a lot on my plate presently though, but will do it soon.

**Comment by ghost** [comment]
Okay, thank you so much! And I understand that of course totally.
