### ISSUE TITLE
Settings Bug

### ISSUE THREAD

**Issue by ghost** [WrichikBasu/ShakeAlarmClock#81]
Hey,

i tried to change the Settings for example the Theme but suddenly the Volume Bar at the bottom in the Settings change too without me clicking on it or changing that...I hope this can be fixed.

**Comment by WrichikBasu** [comment]
Could you please send a screen video? I couldn't reproduce it on my device, hence asking.

**Comment by ghost** [comment]
> Could you please send a screen video? I couldn't reproduce it on my device, hence asking.

Of course. I understand that totally. I added it. Before watching: I never once clicked on the Volume Bar on the bottom. I just clicked the settings at the top and it clicked by itself. And not only by clicking on the first, rather on all it happened the same. I hope this can be fixed.

https://github.com/user-attachments/assets/3eeea2b4-829a-40cc-b024-da9b8778086c

**Comment by WrichikBasu** [comment]
This is a focus issue; the volume setting is not actually changing, just acquiring focus. That's an aesthetic bug.
